default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
  database: find_my_beer_api_development

test:
  <<: *default
  database: find_my_beer_api_test

production:
  <<: *default
  database: find_my_beer_api_production
  username: find_my_beer_api
  password: <%= ENV['FIND_MY_BEER_API_DATABASE_PASSWORD'] %>
